[package]
name = "nimv2"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
utoipa-actix-web = {version="0.1"}
utoipa={version="5", features=["actix_extras", "chrono"]}
serde = {version="1.0", features=["derive"]}
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }
sea-orm = { version = "1.1.14", features = [ "sqlx-postgres","runtime-tokio", "macros", "with-chrono", "mock" ] }
dotenv = "0.15.0"
chrono = "0.4"

[build-dependencies]
utoipa-config = "0.1"
