//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::MediaTypeEnum;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "media")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub tweet_id: i32,
    pub media_type: MediaTypeEnum,
    pub path: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tweet::Entity",
        from = "Column::TweetId",
        to = "super::tweet::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Tweet,
}

impl Related<super::tweet::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tweet.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
