//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "nick")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub password: String,
    pub totp_secret: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tweet::Entity")]
    Tweet,
}

impl Related<super::tweet::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tweet.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
