//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::admin::Entity as Admin;
pub use super::media::Entity as Media;
pub use super::nick::Entity as Nick;
pub use super::tweet::Entity as Tweet;
