//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "media_type_enum")]
pub enum MediaTypeEnum {
    #[sea_orm(string_value = "Pic")]
    Pic,
    #[sea_orm(string_value = "Vid")]
    Vid,
}
