//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tweet")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub content: String,
    pub hash: String,
    pub postat: DateTimeWithTimeZone,
    pub heart: i32,
    pub webvisible: bool,
    pub igvisible: bool,
    pub igid: Option<String>,
    pub supervisor_id: Option<i32>,
    pub nick_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::admin::Entity",
        from = "Column::SupervisorId",
        to = "super::admin::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Admin,
    #[sea_orm(has_many = "super::media::Entity")]
    Media,
    #[sea_orm(
        belongs_to = "super::nick::Entity",
        from = "Column::NickId",
        to = "super::nick::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Nick,
}

impl Related<super::admin::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Admin.def()
    }
}

impl Related<super::media::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Media.def()
    }
}

impl Related<super::nick::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Nick.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
